name: deploy_to_prod

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: "deploy bundle"
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod

  worflow_run:
    name: "Job run for the workflow"
    runs-on: ubuntu-latest
    environment: prod

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - shell: bash
        name: Run pipeline update
        run: |
          databricks bundle run dagm_dabs_demo_job --refresh-all 2>&1 | tee output.log
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod